name: net-core-templates-ci-cd

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0
    - run: dotnet build --configuration Release templates/Microservice/Microservice.WebApi.csproj
